services:
  db:
    image: postgres:15
    container_name: kw-hotel-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kingwilliam
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
    restart: unless-stopped