services:
  db:
    image: postgres:15
    container_name: kw-hotel-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kingwilliam
      TZ: America/Toronto
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    command: postgres -c "timezone=America/Toronto"
    restart: unless-stopped

volumes:
  pg_data: